Voltage <- as.numeric(as.character(working_data$Voltage))
Global_reactive_power <- as.numeric(as.character(working_data$Global_reactive_power))
par(mfrow=c(2,2))
plot(datetime,gap_num, type="l",ylab = "Global Active Power (kilowats)",xlab = "")
plot(datetime,Voltage, type="l",ylab = "Voltage",xlab = "datetime")
plot(datetime,sub_met_1,type="l",xlab="",ylab="Energy sub metering")
par(new=T)
plot(datetime,sub_met_2,type="l",col="red",axes=F,ylim=c(0,40),xlab="",ylab="")
par(new=T)
plot(datetime,sub_met_3,type="l",col="blue",axes=F,ylim=c(0,40),xlab="",ylab="")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty="solid",lwd=2,col=c("black","red","blue"),bty="n")
plot(datetime,Global_reactive_power, type="l",ylab = "Global_reactive_power",xlab = "datetime")
dev.copy(png,'plot4.png')
dev.off()
        
